### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stop' of null

### ISSUE THREAD

**Issue by kvikende** [31i73/atom-dbg-gdb#28]
[Enter steps to reproduce:]

1. Try to debug file without gdb installed or in PATH.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [dbg-gdb](https://github.com/31i73/atom-dbg-gdb) package 1.7.8

### Stack Trace

Uncaught TypeError: Cannot read property 'stop' of null

```
At /Users/torstein/.atom/packages/dbg-gdb/lib/main.coffee:250

TypeError: Cannot read property 'stop' of null
    at /packages/dbg-gdb/lib/main.coffee:250:7
    at /packages/dbg-gdb/lib/main.coffee:332:5
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at BufferedProcess.handleError (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:385:26)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:373:22)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -3:08.2.0 application:reopen-project (input.hidden-input)
     -2:55.7.0 core:confirm (input.hidden-input)
  2x -2:35.7.0 core:backspace (input.hidden-input)
     -2:34.7.0 core:confirm (input.hidden-input)
  3x -2:26.7.0 core:backspace (input.hidden-input)
     -2:22 core:confirm (input.hidden-input)
     -2:12.7.0 core:backspace (input.hidden-input)
     -2:06.8.0 core:confirm (input.hidden-input)
     -1:18.7.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:40.9.0 dbg:custom-debug (span.name.icon.icon-file-text)
     -0:13.8.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-language-rust 0.12.3 
atom-latex 0.8.2 
autocomplete-racer 0.1.3 
busy-signal 1.4.3 
dbg 1.6.3 
dbg-gdb 1.7.8 
intentions 1.1.5 
linter 2.2.0 
linter-rust 0.8.3 
linter-ui-default 1.6.10 
output-panel 0.3.4 
rustsym 0.4.1 
```

**Comment by InnovativeInventor** [comment]
I got this too

**Comment by cerebralweb** [comment]
me too

**Comment by supersaiyansubtlety** [comment]
me too
