### ISSUE TITLE
Output Panel exception

### ISSUE THREAD

**Issue by alexg-k** [31i73/atom-dbg-gdb#48]
Debian Stretch 4.19.0-8-amd64
Atom 1.44.0
dbg-gdb 1.7.8

When I try to debug my dummy program the output panel shows for each console output from the program:
````
Breakpoint 1, main () at findUnique.c:1717       for (i = 0; i < length; i++)e[31mCannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 451, in render
  File "<string>", line 544, in get_term_size
OSError: [Errno 25] Inappropriate ioctl for device
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 453, in render
  File "<string>", line 544, in get_term_size
OSError: [Errno 25] Inappropriate ioctl for devicee[0m
````

Any hints would be much appreciated!

**Comment by alexg-k** [comment]
Turns out the error message was invoked due to a incompatible .gdbinit file!
